version: '3.8'

services:

  postgres:
    image: postgres:latest
    pull_policy: never
    container_name: parking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  
  mongodb:
    image: mongo:7
    container_name: parking-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data:
